routes/web.php
<?php

    use Illuminate\Support\Facades\Route;
    use Illuminate\Support\Facades\Auth;

    /*
    |--------------------------------------------------------------------------
    | Web Routes
    |--------------------------------------------------------------------------
    |
    | Here is where you can register web routes for your application. These
    | routes are loaded by the RouteServiceProvider within a group which
    | contains the "web" middleware group. Now create something great!
    |
    */

    Route::get('/', function () {
        if (Auth::check()) {
            return redirect(\route('home'));
        } else {
            return redirect(\route('login'));
        }
    });

    Auth::routes();

    Route::get('/home', 'HomeController@index')->name('home');

    Route::group(['middleware' => 'auth'], function () {
        Route::get('/tags', 'TagsController@index')->name('tags.index');
        Route::post('/tags/create', 'TagsController@store')->name('tags.store');
        Route::delete('/tags/delete/{tags}', 'TagsController@destroy')->name('tags.destroy');
    });

    Route::resource('categories', 'CategoriesController')->parameters([
        'categories' => 'categories'
    ])->except(['create'])->middleware('auth');
    Route::get('/categories/edit/{categories}', ['as' => 'categories.edit', 'uses' => 'CategoriesController@edit'])->middleware('auth');


    Route::resource('post', 'PostController')->middleware('auth');

    Route::get('gallery/{id}', 'GalleryController@index')->name('gallery.index');
    Route::get('display/{id}', 'GalleryController@show')->name('gallery.show');
    Route::get('download/{id}', 'GalleryController@download')->name('gallery.download');
    Route::post('refresh/{id}', 'GalleryController@refresh')->name('gallery.refresh');
    Route::post('upload/{id}', 'GalleryController@upload')->name('gallery.upload');
    Route::resource('gallery', 'GalleryController')->middleware('auth')->except([
        'index', 'update', 'store', 'show', 'create', 'upload', 'download', 'refresh'
    ]);

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

/**
 * Class Post
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class Post extends Model
{

    use SoftDeletes;

    /**
     * @var string
     */
    protected $table = 'post';

    /**
     * @var string[]
     */
    protected $fillable = [
        'title','seo_slug','content','is_published','user_id'
    ];

    /**
     * @var int[]
     */
    protected $attributes = ['is_published'=>0];

    /**
     * @var string[]
     */
    protected $casts = ['is_published'=>'boolean'];

    /**
     * @var string[]
     */
    protected $dates = ['created_at', 'updated_at', 'deleted_at'];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::saving(function ($model) {
            $model->seo_slug = Str::slug($model->title);
        });
    }

    /**
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo('App\User');
    }

    /**
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function comments()
    {
        return $this->hasMany('App\PostComment');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;

class PostController extends Controller
{
    public function index()
    {
        $posts = Post::latest()->paginate(5);
        return view('post.index', compact('posts'))->with('i', (request()->input('page', 1) - 1) * 5);
    }

    public function create()
    {
        return view('post.create');
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'title'   => 'required|max:255',
            'content' => 'required'
        ]);

        if ($validator->fails())
        {
            $errorMessages = $validator->errors()->getMessages();

            if ($request->ajax())
            {
                return \response()->json(['errors'=>$errorMessages]);
            }else{
                return back()->withErrors($validator)->withInput();
            }

        }

        $post = new Post();
        $post->title = $request->input('title');
        $post->content = $request->input('content');
        $post->is_published = $request->input('is_published');
        $post->user_id = Auth::id();
        $post->save();

        return redirect()->route('post.index')->with('success', 'İşlem Başarıyla Gerçekleşti.');
    }

    public function show(Post $post)
    {
        return view('post.show', compact('post'));
    }

    public function edit(Post $post)
    {
        return view('post.edit', compact('post'));
    }

    public function update(Request $request, Post $post)
    {
        $request->validate([
            'title'   => 'required|max:255',
            'content' => 'required'
        ]);

        $post->update($request->all());

        //return redirect()->route('post.show', $post->getKey())->with('success', 'İşlem Başarıyla Gerçekleşti.');
        return redirect()->route('post.show', $post->getKey())->withToastSuccess('İşlem Başarıyla Gerçekleşti.');
    }

    public function destroy(Post $post)
    {
        // post siler
        // post yorumlarını siler
    }
}

resources/views/post/create.blade.php
@extends('layouts.app')

@section('title', 'Yeni Post Girişi')

@push('scripts')
    <script src="//cdn.ckeditor.com/4.14.1/standard/ckeditor.js"></script>
    <script>
        setTimeout(function () {
            CKEDITOR.replace('content');
        }, 400);
    </script>
@endpush

@section('content')
    <div class="card">
        <div class="card-header">
            @yield('title')
        </div>
        <div class="card-body">
            <form method="POST" action="{{ route('post.store') }}" role="form" autocomplete="off">
                @csrf
                <div class="card-body">
                    <div class="form-group">
                        <label for="title">Başlık</label>
                        <input type="text" class="form-control" name="title" id="title" maxlength="255" placeholder="Başlık">
                    </div>

                    <div class="form-group">
                        <label for="content">İçerik</label>
                        <textarea name="content" class="form-control" id="content" cols="30" rows="10"></textarea>
                    </div>

                    <div class="form-group">
                        <label for="is_published">Yayında</label>
                        <select class="form-control" name="is_published" id="is_published">
                            <option value="1">Evet</option>
                            <option value="0">Hayır</option>
                        </select>
                    </div>
                </div>

                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Kaydet</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/post/edit.blade.php
@extends('layouts.app')

@section('title', $post->title)

@push('scripts')
    <script src="//cdn.ckeditor.com/4.14.1/standard/ckeditor.js"></script>
    <script>
        setTimeout(function () {
            CKEDITOR.replace('content');
        }, 400);
    </script>
@endpush

@section('content')
    <div class="card">
        <div class="card-header">
            @yield('title')
        </div>
        <div class="card-body">
            <form method="POST" action="{{ route('post.update', $post->getKey()) }}">
                @csrf
                @method('PUT')
                <div class="card-body">
                    <div class="form-group">
                        <label for="title">Başlık</label>
                        <input type="text" class="form-control" name="title" id="title" maxlength="255" placeholder="Başlık" value="{{ $post->title ? $post->title : old('title') }}">
                    </div>

                    <div class="form-group">
                        <label for="content">İçerik</label>
                        <textarea name="content" class="form-control" id="content" cols="30" rows="10">{{ $post->content }}</textarea>
                    </div>

                    <div class="form-group">
                        <label for="is_published">Yayında</label>
                        <select class="form-control" name="is_published" id="is_published">
                            <option value="1" {{ $post->is_published == 1 ? "selected=selected" : null }}>Evet</option>
                            <option value="0" {{ $post->is_published == 0 ? "selected=selected" : null }}>Hayır</option>
                        </select>
                    </div>
                </div>

                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Kaydet</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/post/index.blade.php
@extends('layouts.app')

@section('title', 'Postlar')

@section('actions')
    <a href="{{ route('post.create') }}" class="btn btn-success"><i class="fa fa-plus"></i> Yeni Oluştur</a>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="mb-3 card">
                <div class="card-body">
                    <div class="table-responsive">
                        @if ($posts->count() > 0)
                            <p><b>Toplam Kayıt Sayısı:</b> {{ $posts->count() }}</p>
                        @endif

                        <table class="table table-bordered table-striped table-hover mb-0">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Başlık</th>
                                <th>Yayında</th>
                                <th>Oluşturan Kullanıcı</th>
                                <th>Eklenme Tarihi</th>
                                <th style="width: 20%"></th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse ($posts as $item)
                                <tr>
                                    <td>{{ ++$i }}</td>
                                    <td>{{ $item->title }}</td>
                                    <td>{{ $item->is_published == 1 ? 'Evet' : 'Hayır' }}</td>
                                    <td>{{ $item->user->name }}</td>
                                    <td>{{ $item->created_at->format('d.m.Y H:i:s') }}</td>
                                    <td style="text-align: center;">
                                        <form action="{{ route('post.destroy', $item->getKey()) }}" method="POST">
                                            <a class="btn btn-info btn-sm" title="Görüntüle" href="{{ route('post.show', $item->getKey()) }}">
                                                <i class="fa fa-eye"></i>
                                            </a>

                                            <a class="btn btn-primary btn-sm" title="Düzenle" href="{{ route('post.edit', $item->getKey()) }}">
                                                <i class="fa fa-edit"></i>
                                            </a>

                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Bu postu silmek istediğinize emin misiniz?')">
                                                <i class="fa fa-trash"></i>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="6">Kayıt Bulunamadı.</td>
                                </tr>
                            @endforelse
                            </tbody>
                        </table>
                    </div>

                    <div class="mt-3">
                        {!! $posts->links() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/post/show.blade.php
@extends('layouts.app')

@section('title', $post->title)

@section('actions')
    <a href="{{ route('gallery.index', $post->getKey()) }}" class="btn btn-primary"><i class="fa fa-arrow-right"></i> Galeriye Git</a>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="mb-3 card">
                <div class="card-header">
                    <span class="text-bold">İçerik</span>
                </div>
                <div class="card-body">
                    {!! $post->content !!}
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="mb-3 card">
                <div class="card-header">
                    <span class="text-bold">Diğer Bilgiler</span>
                </div>
                <div class="card-body table-responsive">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th style="width: 20%">Başlık</th>
                            <td style="width: auto">{{ $post->title }}</td>
                        </tr>
                        <tr>
                            <th>Seo Slug</th>
                            <td>{{ $post->seo_slug }}</td>
                        </tr>
                        <tr>
                            <th>Yayında</th>
                            <td>{{ $post->is_published == 1 ? 'Evet' : 'Hayır' }}</td>
                        </tr>
                        <tr>
                            <th>Oluşturan Kullanıcı</th>
                            <td>{{ $post->user->name }}</td>
                        </tr>
                        <tr>
                            <th>Eklenme Tarihi</th>
                            <td>{{ $post->created_at->format('d.m.Y H:i:s') }}</td>
                        </tr>
                        <tr>
                            <th>Güncellenme Tarihi</th>
                            <td>{{ $post->created_at->format('d.m.Y H:i:s') }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection