routes/web.php
<?php

    use Illuminate\Support\Facades\Route;
    use Illuminate\Support\Facades\Auth;

    /*
    |--------------------------------------------------------------------------
    | Web Routes
    |--------------------------------------------------------------------------
    |
    | Here is where you can register web routes for your application. These
    | routes are loaded by the RouteServiceProvider within a group which
    | contains the "web" middleware group. Now create something great!
    |
    */

    Route::get('/', function () {
        if (Auth::check()) {
            return redirect(\route('home'));
        } else {
            return redirect(\route('login'));
        }
    });

    Auth::routes();

    Route::get('/home', 'HomeController@index')->name('home');

    Route::group(['middleware' => 'auth'], function () {
        Route::get('/tags', 'TagsController@index')->name('tags.index');
        Route::post('/tags/create', 'TagsController@store')->name('tags.store');
        Route::delete('/tags/delete/{tags}', 'TagsController@destroy')->name('tags.destroy');
    });

    Route::resource('categories', 'CategoriesController')->parameters([
        'categories' => 'categories'
    ])->except(['create'])->middleware('auth');
    Route::get('/categories/edit/{categories}', ['as' => 'categories.edit', 'uses' => 'CategoriesController@edit'])->middleware('auth');


    Route::resource('post', 'PostController')->middleware('auth');

    Route::get('gallery/{id}', 'GalleryController@index')->name('gallery.index');
    Route::get('display/{id}', 'GalleryController@show')->name('gallery.show');
    Route::get('download/{id}', 'GalleryController@download')->name('gallery.download');
    Route::post('refresh/{id}', 'GalleryController@refresh')->name('gallery.refresh');
    Route::post('upload/{id}', 'GalleryController@upload')->name('gallery.upload');
    Route::resource('gallery', 'GalleryController')->middleware('auth')->except([
        'index', 'update', 'store', 'show', 'create', 'upload', 'download', 'refresh'
    ]);

app/Gallery.php
<?php

    namespace App;

    use Illuminate\Database\Eloquent\Model;

    /**
     * Class Gallery
     * @package App
     * @mixin \Illuminate\Database\Eloquent\Builder
     */
    class Gallery extends Model
    {
        const UPDATED_AT = null;

        /**
         * @var string
         */
        public $table = 'gallery';

        /**
         * @var string[]
         */
        protected $fillable = [
            'post_id','name','file_name','user_id'
        ];

        /**
         * @var string[]
         */
        protected $dates = ['created_at','updated_at'];

        /**
         *
         * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
         */
        public function post()
        {
            return $this->belongsTo('App\Post');
        }

        /**
         *
         * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
         */
        public function user()
        {
            return $this->belongsTo('App\User');
        }
    }

app/Http/Controllers/GalleryController.php
<?php

namespace App\Http\Controllers;

use App\Gallery;
use App\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\View\View;

class GalleryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param $id
     * @return \Illuminate\Http\Response|View
     */
    public function index($id)
    {
        $post = Post::findOrFail($id);

        $gallery = Gallery::where('post_id', $post->getKey())->get();
        return view('gallery.index', compact('gallery', 'post'));
    }

    /**
     * Display the specified resource.
     *
     * @param $id
     */
    public function show($id)
    {
        $gallery = Gallery::findOrFail($id);

        $folder = public_path('uploads');

        $path = $folder . DIRECTORY_SEPARATOR . $gallery->file_name;
        if (file_exists($path)){
            return response()->file($path);
        }
        else {
            return redirect()->route('gallery.index', $gallery->post_id)->withToastError('Dosya mevcut değil!');
        }
    }

    public function download($id){
        $gallery = Gallery::findOrFail($id);

        $folder = public_path('uploads');
        $path = $folder . DIRECTORY_SEPARATOR . $gallery->file_name;

        if (file_exists($path))
        {
            return response()->download($path);
        }else{
            return redirect()->route('gallery.index', $gallery->post_id)->withToastError('Dosya mevcut değil!');
        }
    }

    public function upload($id, Request $request)
    {
        $post = Post::findOrFail($id);

        if ($request->hasFile('file'))
        {
            // Upload path
            $destinationPath = 'uploads/';

            // Create directory if not exists
            if (!is_dir($destinationPath))
            {
                @mkdir($destinationPath, 0755, true);
            }

            // Get file extension
            $extension = $request->file('file')->getClientOriginalExtension();

            // Valid extensions
            $validExtensions = ['jpeg','jpg','png','pdf'];

            // Check extension
            if(in_array(strtolower($extension), $validExtensions))
            {
                // Rename file
                $fileName = uniqid().time().'.'.$extension;

                // Uploading file to given path
                $request->file('file')->move($destinationPath, $fileName);

                $gallery = new Gallery();
                $gallery->post_id = $post->getKey();
                $gallery->name = $request->file('file')->getClientOriginalName();
                $gallery->file_name = $fileName;
                $gallery->user_id = Auth::id();
                $gallery->save();
            }
        }
    }

    public function refresh($id)
    {
        $post = Post::findOrFail($id);

        $gallery = Gallery::where('post_id', $post->getKey())->get();
        return view('gallery.view.items', compact('gallery'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Gallery  $gallery
     */
    public function destroy(Gallery $gallery)
    {
        $post = Post::findOrFail($gallery->post_id);

        $folder = public_path('uploads');
        $path = $folder. DIRECTORY_SEPARATOR . $gallery->file_name;
        if (file_exists($path))
        {
            @unlink($path);
        }

        $gallery->delete();

        return redirect()->route('gallery.index', $post->getKey())->withToastSuccess('Silme İşlemi Gerçekleşti.');
    }
}

resources/views/gallery/index.blade.php
@php
    /* @var $post \App\Post */
@endphp

@extends('layouts.app')

@section('title', $post->title)

@section('actions')
    <a href="{{ route('post.show', $post->getKey()) }}" class="btn btn-success"><i class="fa fa-arrow-left"></i> Post</a>
@endsection

@push('styles')
    <link rel="stylesheet" href="{{ asset('dropzone/dist/min/dropzone.min.css') }}">
@endpush

@push('scripts')
    <script src="{{ asset('dropzone/dist/min/dropzone.min.js') }}" type="text/javascript"></script>
    <script>
        var CSRF_TOKEN = document.querySelector('meta[name="csrf-token"]').getAttribute("content");

        Dropzone.options.dropzone = {
            acceptedFiles: ".jpeg, .jpg, .png, .pdf",
            complete: function (file) {
                var $data_url = $("#dropzone").data("url");

                $.post($data_url, {_token: CSRF_TOKEN}, function(response){

                    $(".gallery-list-container").html(response);

                });
            }
        };
    </script>
@endpush

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="mb-3 card">
                <div class="card-body">
                    <form action="{{ route('gallery.upload', $post->getKey()) }}" id="dropzone" class="dropzone" data-plugin="dropzone" data-url="{{ route('gallery.refresh', $post->getKey()) }}">
                        @csrf
                        <div class="dz-message">
                            <h3 class="m-h-lg">Yüklemek istediğiniz resimleri buraya sürükleyiniz</h3>
                            <p class="m-b-lg text-muted">(Yüklemek için dosyalarınızı sürükleyiniz yada buraya tıklayınız)</p>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="gallery-list-container">
        @include('gallery.view.items', ['gallery' => $gallery, 'post' => $post])
    </div>
@endsection